### ISSUE TITLE
Have some kind of status document that describes the current state of the engine/browser

### ISSUE THREAD

**Issue by jaytaph** [jaytaph/gosub-browser#18]
This would help with people who want to know what is happening with the browser.

**Comment by TheFanatr** [comment]
Hey! Cool project. Was just browsing the issues and came across this one. I think it would be interesting to have a document, maybe called `Quirks.md`, that all substantial edits, or at least all pull requests, must update to help further describe the technicalities of the project as per the edit's technical changes. Thanks.

**Comment by jaytaph** [comment]
Good idea. For now, I've setup a [discussion board](https://github.com/jaytaph/gosub-browser/discussions) so we can discuss things without polluting the issue list.
