### ISSUE TITLE
Split browser components into their separate repo's?

### ISSUE THREAD

**Issue by jaytaph** [jaytaph/gosub-browser#20]
Currently the "browser" is nothing more than a html5 to node-tree parser, or at least, that is what it will be. The library it generates is `gosub-engine`, but this repo also contains a few tools (`[parser|tokenizer]-tests), and a "browser", that should do nothing more than reading an url, and parsing the html5 tree.

If we move to a separate organisation (see #17), we could rename this repo to "gosub-engine", and have a separate "gosub-browser", "gosub-text-browser" etc, to split the different components. This would also mean that it would be easier to use the gosub-engine for anyone else for their own usage.

I'd like to get some input from others about this.

**Comment by emwalker** [comment]
Personal take — putting much effort into this at this point might be premature in the life of this project.  Re-implementing a browser is a big task, to put it mildly.  What you probably want to do first is to prove out the concept and gain traction.

Rust's module system is first-class, and it's easy to split out separate crates within the same repo if needed, [using a workspace](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html).  This allows you to keep a single monorepo until that becomes unweildy.

A similar thought with regard to creating a new organization for the project.  I'd let it gain traction first until hosting things in your personal account gets in the way.

**Comment by jaytaph** [comment]
fair enough. I'll leave it for now.
