### ISSUE TITLE
Server for Gosub Site not Found at Web Domain (Gosub.io)

### ISSUE THREAD

**Issue by TheFanatr** [jaytaph/gosub-browser#28]
Hey! Stumbled across this project in my recommended. Seems like you've listed some meta-tasks in the issues so far, so I figured I'd help, and add one for the site; [Gosub.io](//Gosub.io) seems to [not be resolving to a web server](https://viewdns.info/ismysitedown/?domain=gosub.io), although it's [DNS records](https://viewdns.info/dnsrecord/?domain=gosub.io) do show it as being registered with [OpenProvider](//OpenProvider.com). Is this just not configured, or is there work to be done, such as making and/or linking-up a GitHub Pages site? Thanks!

**Comment by jaytaph** [comment]
Hi there!

Yes, there is work to be done. The site is just registered and to be honest, there isn't much to put up there. Maybe a redirect to the github would be good enough for now I guess.

**Comment by jaytaph** [comment]
I've setup a simple page with nothing much than a link to the repository.

![image](https://github.com/jaytaph/gosub-browser/assets/241458/4128c0c6-18f7-42df-bfd6-fe795d4175e6)

This should be enough for now probably. But if somebody wants to setup something better, i'm all for it!

**Comment by bigfatbird** [comment]
The SSL-Cert is not working for me atm, the site is flagged as dangerous 
![grafik](https://github.com/jaytaph/gosub-browser/assets/1159341/e03567b3-e73f-4ba9-a844-33ce00e83394)


Just an Idea: To not mix up your personal projects with this one you could migrate the relevant repos to an organization, so people can find everything regarding gosub

**Comment by jaytaph** [comment]
@bigfatbird  This should be fixed now.  letsencrypt didn't add gosub.io, but that is fixed now.

**Comment by bigfatbird** [comment]
@jaytaph Cool, yes i can see the site now

**Comment by jaytaph** [comment]
> Just an Idea: To not mix up your personal projects with this one you could migrate the relevant repos to an organization, so people can find everything regarding gosub

True, but we want to wait until we gain a bit of traction. As soon as there is something to show to the (developer) public, we probably will move to an better repository home

**Comment by bigfatbird** [comment]
@jaytaph I also had the same error when browsing to your personal HP, fyi

https://www.adayinthelifeof.nl/

**Comment by jaytaph** [comment]
Not yet as there is no real site at the moment (just a single html page)..  Maybe we should set one up, and in that case, we might switch to a separate organisation as well? (/cc @emwalker).

**Comment by jaytaph** [comment]
> @jaytaph I also had the same error when browsing to your personal HP, fyi

thanks for the headsup. It seems that directadmin on that system somehow didn't add the `www` subdomains for generated domains. This should be fixed by generating the certs again (i'm not sure why this is happening, hasn't in the passed)

**Comment by emwalker** [comment]
> Maybe we should set one up, and in that case, we might switch to a separate organisation as well? (/cc @emwalker).

I don't want to dampen people's enthusiasm, so don't mind my reservations to setting up an organization yet.  I think I'd wait until
1. People are sure about the name "Gosub."  To my American ears, this sounds like a combination of Golang and something.  Is it a good name for a browser? I'm on the fence.  Perhaps it's neutral enough and has few enough connotations that it can be made to work.
2. The project demonstrates that it has momentum and skilled contributors and will be around for a while.

If people in this thread think that (1) and (2) are already satisfied, then I wouldn't wait.

**Comment by jaytaph** [comment]
The name is just a working title. I'm not married to the name by itself and it should be fairly easy to change if needed (trademarks or anything for instance). I'm happy to hear alternatives, but it's something that doesn't have any priority right now I guess.

I think it's wise to wait, but since we already have a "website", it might make sense to bundle them (it's cheap enough to make an organisation). I definitely don't think we satisfied both points at the moment, so I just leave the gosub-browser repo on my personal branch, and see what we do with other repo's comes the time we need to have more repos and need more fine-grained control on repo's, teams and people.  

I have created an origanisation though and placed the main html page on there since there isn't anything useful we need to do there at the moment. We just don't need to spread the word to that organisation at the moment.

**Comment by jaytaph** [comment]
I think the site itself now has a placeholder with a link to the repository. There isn't much to do at the moment for as long as we cannot really demonstrate anything yet.

Maybe we could add some text about the project itself, and what goals it tries to achieve but I think for now it has very low priority.
