### ISSUE TITLE
How will this browser "push back" against negative news?

### ISSUE THREAD

**Issue by szalapski** [jaytaph/gosub-browser#5]
[After reading this post](https://adayinthelifeof.nl/2023/09/22/browsers.html), I feel like something is missing.  

"...I do like to follow tech news...but I started to get the same feeling I had ten years ago: it’s all negative."  "I am going to write a browser. For two reasons: I want this to be a way to push back. Just a tiny amount."

I am not getting the meat of the vision here: how this new browser will push back against negative news.  Will it be a positive-news-only browser?  Or will it block access to deceptive, negative, or otherwise unhealthy content?  Or something else?

**Comment by jolfosh** [comment]
> [After reading this post](https://adayinthelifeof.nl/2023/09/22/browsers.html), I feel like something is missing.
> 
> "...I do like to follow tech news...but I started to get the same feeling I had ten years ago: it’s all negative." "I am going to write a browser. For two reasons: I want this to be a way to push back. Just a tiny amount."
> 
> I am not getting the meat of the vision here: how this new browser will push back against negative news. Will it be a positive-news-only browser? Or will it block access to deceptive, negative, or otherwise unhealthy content? Or something else?

From my understanding, the browser is a small way to fight back from the inevitable conglomeration of proprietary browsers with privacy destroying requirements. When the author wrote about the news, I believe they were setting the stage for how they felt in the moment to explain or justify their motivation for creating the browser.

**Comment by jaytaph** [comment]
It's not even about the browser. It will not do anything magic privacy wise, but should be a regular browser that is free, and doesn't spend all its time on finding new ways to display ads or invade your privacy. If somebody wants to write an adblocker for it, it should be possible and should not be stopped by any company whatsoever.  It's my (feeble) attempt on doing "something" against what I think is wrong with tech today.  Hope this explains it a bit
