### ISSUE TITLE
Make sure we cannot create recursive node trees

### ISSUE THREAD

**Issue by jaytaph** [jaytaph/gosub-browser#59]
Right now it is possible to create a node with a child that points to itself. This causes an endless loop.

We have to make sure we cannot add nodes that result in such a loop.

**Comment by mihna123** [comment]
Would it just be enough to make sure that the children ids are never equal to the parent id?

**Comment by mihna123** [comment]
But then i guess it doesn't work if it goes more than one level deep

**Comment by lucalewin** [comment]
I would implement a arena using a `Vec` like this:

```rust
pub struct Arena<T> {
    nodes: Vec<Node<T>>
}

pub struct Node<T> {
    pub id: usize,
    pub parent: Option<usize>,
    pub children: Vec<usize>,
    pub data: T
}

impl<T> Arena<T> {
    pub fn new() -> Self {
        Self { nodes: Vec::new() }
    }

    pub fn get(&self, id: usize) -> Option<&Node<T>> {
        self.nodes.get(id)
    }

    pub fn get_mut(&mut self, id: usize) -> Option<&mut Node<T>> {
        self.nodes.get_mut(id)
    }

    pub fn add(&mut self, data: T) -> usize {
        let id = self.nodes.len();

        self.nodes.push(Node { id, parent: None, children: Vec::new(), data });

        id
    }

    pub fn attach(&mut self, parent_id: usize, child_id: usize) {
        if let Some(parent) = self.nodes.get_mut(parent_id) {
            parent.children.push(child_id);
        }

        if let Some(child) = self.nodes.get_mut(child_id) {
            child.parent = Some(parent_id);
        }
    }
}
```

Then we could create a `DomNode` struct:

```rust
pub struct DomNode {
    /// name of the node, or empty when it's not a tag
    pub name: String,
    /// namespace of the node
    pub namespace: Option<String>,
    /// actual data of the node
    pub data: NodeData,
}

/// Different type of node data
#[derive(Debug, PartialEq, Clone)]
pub enum NodeData {
    Document,
    Text {
        value: String,
    },
    Comment {
        value: String,
    },
    Element {
        name: String,
        attributes: HashMap<String, String>,
    },
}
```

This can then be used like this:

```rust
let mut arena = Arena::<DomNode>::new();

let node_id = arena.add(DomNode {
    name: "".into(),
    namespace: None,
    data: NodeData::Document
});
```

This has the advantage that the arena can be used for different node types (could be reused for the css parser)

One drawback would be that we cannot remove nodes because the node ids would then change (if that is necessary then an inplementation with a `HashMap` would make sense again.

**Comment by jaytaph** [comment]
There is an arena like system for the current nodes, so maybe we can expand this a bit to make it more flexible. The nodes are added to a `document`, which is merely an arena of nodes, plus the root node of the tree.  We could check during attachment of nodes if any cyclic references are present or not.

**Comment by lucalewin** [comment]
Sounds like a good idea to check that. I think in my implementation cyclic are possible too without that check.

I tried replacing the current arena in my fork and got all tests to pass but I'm not quite happy with the implementation. Maybe you want to take a look (don't want to make a pull request for this)
https://github.com/lucalewin/gosub-browser/blob/arena/src/html5_parser/arena.rs

**Comment by Kiyoshika** [comment]
If this was merged, can this issue be closed now?
