### ISSUE TITLE
Consider folking chromium

### ISSUE THREAD

**Issue by avin-kavish** [jaytaph/gosub-browser#7]
Writing a full standard compliant browser is no trivial task. It's probably 20 years+ task even with google's resource, you can see how that's going.

Consider folking chromium  and making something like Vivaldi if privacy is your goal.

**Comment by jaytaph** [comment]
This is true. It's not an easy task, or a task that quite possibly be finished. But that is not a reason to not start one. The amount of html5 tokenizers and parsers I find online are inspiring, as 99% of them are just experimental code ramblings from people who are trying out and feeding their curiosity. We should have more of these, not less.  Chromium is a great engine that will develop just find without me :)  But i want to know more about browsers, and when I get angry reading the next tech news about some company screwing me over, I'd rather write some code that can benefit others, than getting my frustration out in the boxing ring or sports club.   Hope this helps..
